aiohttp==3.9.1
aiosignal==1.3.1
annotated-types==0.6.0
anyio==3.7.1
appnope==0.1.3
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
asgiref==3.7.2
asttokens==2.2.1
async-lru==2.0.3
async-timeout==4.0.3
attrs==23.1.0
Babel==2.12.1
backcall==0.2.0
beautifulsoup4==4.12.2
bleach==6.0.0
blinker==1.7.0
certifi==2023.5.7
cffi==1.15.1
charset-normalizer==3.2.0
chembl-webresource-client==0.10.8
click==8.1.7
comm==0.1.3
contourpy==1.1.0
cycler==0.11.0
dataclasses-json==0.6.3
debugpy==1.6.7
decorator==4.4.2
defusedxml==0.7.1
distlib==0.3.6
distro==1.9.0
Django==5.0.1
docutils==0.20.1
easydict==1.10
exceptiongroup==1.1.2
executing==1.2.0
fastjsonschema==2.17.1
ffmpeg==1.4
filelock==3.12.2
Flask==3.0.0
fonttools==4.41.0
fqdn==1.5.1
frozenlist==1.4.1
fsspec==2023.12.2
graphviz==0.20.1
h11==0.14.0
httpcore==1.0.2
httpx==0.26.0
idna==3.4
imageio==2.32.0
imageio-ffmpeg==0.4.9
ipykernel==6.24.0
ipython==8.14.0
ipython-genutils==0.2.0
ipywidgets==8.0.7
isoduration==20.11.0
itsdangerous==2.1.2
jedi==0.18.2
Jinja2==3.1.2
joblib==1.3.2
json5==0.9.14
jsonpatch==1.33
jsonpointer==2.4
jsonschema==4.18.4
jsonschema-specifications==2023.7.1
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.6.3
jupyter-lsp==2.2.0
jupyter_client==8.3.0
jupyter_core==5.3.1
jupyter_server==2.7.0
jupyter_server_terminals==0.4.4
jupyterlab==4.0.3
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.8
jupyterlab_server==2.23.0
kiwisolver==1.4.4
langchain==0.0.353
langchain-community==0.0.7
langchain-core==0.1.4
langsmith==0.0.77
MarkupSafe==2.1.3
marshmallow==3.20.1
matplotlib==3.7.2
matplotlib-inline==0.1.6
mistune==3.0.1
MouseInfo==0.1.3
moviepy==1.0.3
mpmath==1.3.0
multidict==6.0.4
mypy-extensions==1.0.0
mysql-connector-python==8.1.0
nbclient==0.8.0
nbconvert==7.7.2
nbformat==5.9.1
nest-asyncio==1.5.6
networkx==3.2.1
notebook==7.0.0
notebook_shim==0.2.3
numpy==1.25.2
openai==1.6.1
overrides==7.3.1
packaging==23.2
padelpy==0.1.14
pandas==2.0.3
pandocfilters==1.5.0
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==10.0.0
platformdirs==3.8.1
proglog==0.1.10
prometheus-client==0.17.1
prompt-toolkit==3.0.39
protobuf==4.21.12
psutil==5.9.5
ptyprocess==0.7.0
pure-eval==0.2.2
pyarrow==12.0.1
PyAutoGUI==0.9.54
pycparser==2.21
pydantic==2.5.3
pydantic_core==2.14.6
pydotplus==2.0.2
PyGetWindow==0.0.9
Pygments==2.15.1
pylance==0.6.2
PyMsgBox==1.0.9
pynput==1.7.6
pyobjc-core==10.1
pyobjc-framework-ApplicationServices==10.1
pyobjc-framework-Cocoa==10.1
pyobjc-framework-CoreText==10.1
pyobjc-framework-Quartz==10.1
pyparsing==3.0.9
pyperclip==1.8.2
PyQt5==5.15.10
PyQt5-Qt5==5.15.11
PyQt5-sip==12.13.0
PyRect==0.2.0
PyScreeze==0.1.30
python-dateutil==2.8.2
python-json-logger==2.0.7
pytube==15.0.0
pytweening==1.0.7
pytz==2023.3
pywhatkit==5.4
PyYAML==6.0.1
pyzmq==25.1.0
qtconsole==5.4.3
QtPy==2.3.1
referencing==0.30.0
requests==2.31.0
requests-cache==0.7.5
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rpds-py==0.9.2
rubicon-objc==0.4.7
scikit-learn==1.3.2
scipy==1.11.3
seaborn==0.13.0
Send2Trash==1.8.2
six==1.16.0
sniffio==1.3.0
soupsieve==2.4.1
SQLAlchemy==2.0.25
sqlparse==0.4.4
stack-data==0.6.2
statistics==1.0.3.5
sympy==1.12
tabulate==0.9.0
tenacity==8.2.3
terminado==0.17.1
threadpoolctl==3.2.0
tinycss2==1.2.1
tomli==2.0.1
torch==2.1.2
tornado==6.3.2
tqdm==4.66.1
traitlets==5.9.0
typing-inspect==0.9.0
typing_extensions==4.7.1
tzdata==2023.3
uri-template==1.3.0
url-normalize==1.4.3
urllib3==2.0.4
virtualenv==20.23.1
wcwidth==0.2.6
webcolors==1.13
webencodings==0.5.1
websocket-client==1.6.1
Werkzeug==3.0.1
widgetsnbextension==4.0.8
wikipedia==1.4.0
yarl==1.9.4
youtube-dl==2021.12.17
